version: "3"

networks:
  public: {}

services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    hostname: localhost
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: "testtopic:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - "9090:9090"
    networks:
      - public
    volumes:
      - ${PWD}/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/config/targets/prometheus.json:/etc/prometheus/targets/prometheus.json
      - ${PWD}/config/targets/grafana.json:/etc/prometheus/targets/grafana.json
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:6.1.1
    ports:
      - "3000:3000"
    networks:
      - public
    volumes:
      - ${PWD}/config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml      
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
