version: "3"

networks:
  public: {}

services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    hostname: localhost
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: "testtopic:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      
  prometheus:
    build: './prometheus'
    container_name: 'prometheus'
    networks:
        - public
    ports:
      - '9090:9090'

  grafana:
    build: './grafana'
    container_name: 'grafana'
    networks:
      - public
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret